service: my-sls-scraper
# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  profile: Aws-tour profile
  logRetentionInDays: 1
  environment:
      HTTP_CACHE_BUCKET_NAME: !Ref HttpCacheBucket
      FEED_BUCKET_NAME: !Ref ScraperFeedBucket
      ECS_CLUSTER: !GetAtt FargateECSCluster.Arn
      ECS_TASK_ARN: !Ref FargateECSTaskDefinition
      ECS_SUBNET: !Ref FargateSubnet
      ECS_SEC_GROUP: !Ref FargateSG
      CONTAINER_NAME: "scraper_container"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:ListBucket"   
      Resource: 
        - !Sub
           - "arn:aws:s3:::#{BucketName}/*"
           - BucketName: !Ref HttpCacheBucket
        - !Sub
           - "arn:aws:s3:::#{BucketName}"
           - BucketName: !Ref HttpCacheBucket
    
    - Effect: Allow
      Action:
        - ecs:RunTask

      Resource:
        - !Ref FargateECSTaskDefinition

    - Effect: Allow
      Action:
        - iam:PassRole

      Resource: 
        - !GetAtt FargateExecutionRole.Arn

    - Effect: Allow
      Action:
        - iam:PassRole
      Resource: 
        - !GetAtt FargateTaskRole.Arn



functions:
  pollSpidersScrape:
      handler: handler.run_crawlers
      events:
        - schedule:
             rate: rate(2 hours)
             enabled: true
             description: Poll spiders every 2 hours
# We include files by whitelisting to reduce the deployment time.
# Just remember to add any files you create!
package:
  include:
    - handler.py
    - launcher.py
    - launch_fargate.py
    - my_sls_scraper/**
    - scrapy.cfg
  exclude:
    - "./**"

resources:
  - AWSTemplateFormatVersion: "2010-09-09"
    Transform: "AWS::Serverless-2016-10-31"
  - ${file(./s3-template.yml)}
  - ${file(./fargate-template.yml)}

plugins:
  - serverless-python-requirements
  - serverless-cloudformation-sub-variables

custom:
  pythonRequirements:
    slim: true # Omits tests, __pycache__, *.pyc etc from dependencies
    fileName: requirements.txt